name: Build, Push, and Deploy to Koob

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-variables.outputs.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Variables
        id: set-variables
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "image_tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to Koob cluster
    runs-on: ubuntu-latest
    needs: build
    env:
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.K3S_CONFIG }} | base64 --decode > ~/.kube/config
          export KUBECONFIG=~/.kube/config

      - name: Check cluster
        run: kubectl get nodes

      - name: Replace Placeholders in Kubernetes Manifests
        run: |
          # Escape special characters in values
          ESCAPED_APP_NAME=$(echo "${{ secrets.IMAGE_NAME }}" | sed 's/[\/&]/\\&/g')
          ESCAPED_IMAGE_TAG=$(echo "${{ env.IMAGE_TAG }}" | sed 's/[\/&]/\\&/g')
          ESCAPED_DOCKER_REGISTRY=$(echo "${{ secrets.DOCKER_REGISTRY }}" | sed 's/[\/&]/\\&/g')

          # Replace placeholders in deployment.yaml
          sed -i "s/{{APP_NAME}}/$ESCAPED_APP_NAME/g" .github/k8s/deployment.yaml
          sed -i "s/{{IMAGE_TAG}}/$ESCAPED_IMAGE_TAG/g" .github/k8s/deployment.yaml
          sed -i "s/{{DOCKER_REGISTRY}}/$ESCAPED_DOCKER_REGISTRY/g" .github/k8s/deployment.yaml

          # Replace placeholders in service.yaml
          sed -i "s/{{APP_NAME}}/$ESCAPED_APP_NAME/g" .github/k8s/service.yaml

      - name: Debug Generated YAML
        run: |
          echo "Deployment YAML:"
          cat .github/k8s/deployment.yaml
          echo "Service YAML:"
          cat .github/k8s/service.yaml

      - name: Deploy App (Deployment)
        run: kubectl apply -f .github/k8s/deployment.yaml

      - name: Deploy App (Service)
        run: kubectl apply -f .github/k8s/service.yaml    
